### ISSUE TITLE
handrankmap not being generated correctly?

### ISSUE THREAD

**Issue by voraz415** [ozzi7/Poker-MCCFRM#1]
![image](https://user-images.githubusercontent.com/53714275/68412790-be929180-0141-11ea-931e-dc38aa660fa5.png)

Null reference exception here. How to fix?

**Comment by ozzi7** [comment]
Hello @voraz415, the reason you got this error is because the hand evaluator was not initialized properly. The newest commit fixes it. Note that this project is a work in progress.
