### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by moreheadm** [ozzi7/Poker-MCCFRM#7]
This repository is interesting to me, but it currently has no open source license. This makes it hard to use, at least in my country (the U.S.). Good choices for licenses are the MIT License (if you're okay with people using and modifying the code for any purpose with no condition) or the GPL/AGPL (if you want people who redistribute the software to make their changes available).

If you're not interested in making it open source, maybe you could clarify the conditions for using it for in the README, or just ignore this issue.

I could submit a PR with a license if that makes it easier.

Thanks! Great project.

**Comment by ozzi7** [comment]
Added a license, thanks!
