### ISSUE TITLE
Cpp-Version Source

### ISSUE THREAD

**Issue by ghost** [ozzi7/Poker-MCCFRM#9]
?

**Comment by dmitrynvm** [comment]
Please, help me with with issue, I really need the solution for C++ (available on dmitrynvm@gmail.com).
There are some issues and difficutlies with C# version, it does not proceed well.

**Comment by dmitrynvm** [comment]
We need your help, bro. There are troubles with execution on C#. I am not C# programmer to fix the underlying troubles. Pls, give me a Cpp version to debug and play with it, I could even contribute your work.
Thanks for the implementation, it is amazing with respect to others like ACPC.

**Comment by dmitrynvm** [comment]
Need your help, man
